### ISSUE TITLE
Ladestatus und Ladezeit werden nicht aktualisiert

### ISSUE THREAD

**Issue by Kai9555** [vikt0rm/dbus-goecharger#3]
Hi,

installiert nach Anleitung direkt auch dem Multiplus, dennoch werden Status (Verbunden, nicht verbunden) und Ladezeit nicht angezeigt.

Hat jemand eine Idee? Auch ist die Anzeige im Dashboard bei Victron überlagert?!

Das Log läuft mit folgendem Fehler voll:
````
2023-03-06 07:45:44,820 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 189, in _update
    self._dbusservice['/MCU/Temperature'] = int(data['tmp'])
KeyError: 'tmp'
2023-03-06 07:45:45,127 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 189, in _update
    self._dbusservice['/MCU/Temperature'] = int(data['tmp'])
KeyError: 'tmp'
2023-03-06 07:45:45,350 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 189, in _update
    self._dbusservice['/MCU/Temperature'] = int(data['tmp'])
KeyError: 'tmp'
2023-03-06 07:45:45,646 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 189, in _update
    self._dbusservice['/MCU/Temperature'] = int(data['tmp'])
KeyError: 'tmp'
2023-03-06 07:45:45,844 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 189, in _update
    self._dbusservice['/MCU/Temperature'] = int(data['tmp'])
KeyError: 'tmp'
````

<img width="770" alt="Bildschirm­foto 2023-03-06 um 08 34 25" src="https://user-images.githubusercontent.com/56715979/223046491-041f087b-a5da-4c25-b619-14279697f263.png">

**Comment by domii666** [comment]
selbes Problem bei mir

**Comment by MauriceFaber** [comment]
Habe das gleiche Problem. 
Und die Lade-Leistung wird, wie im Screenshot, nicht angezeigt.

**Comment by Justballer** [comment]
Hallo,
ich habe ein ähnliches Problem, evtl. gleicher Fehler. Nach Neustarten des Scripts geht die Anzeige wunderbar. Das bleibt auch, solange ich die GoE über die GoE-App starte und beende. Mache ich das gleiche aber über das Auto oder über die Tesla App, dann hängt sich anscheinend das Script auf. Die Anzeige im VRM ist eingefroren und das "current.log" bleibt leer.
Führe ich nun im PuTTY ein "/restart.sh" durch, dann läuft die Anzeige im VRM wieder und im logfile steht folgendes:

2023-10-04 14:03:39,993 root CRITICAL Error at _update
_Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 166, in _update
    data = self._getGoeChargerData()
  File "/data/dbus-goecharger/dbus-goecharger.py", line 146, in _getGoeChargerData
    json_data = request_data.json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 889, in json
    return complexjson.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1069 (char 1068)
2023-10-04 14:05:47,501 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 166, in _update
    data = self._getGoeChargerData()
  File "/data/dbus-goecharger/dbus-goecharger.py", line 146, in _getGoeChargerData
    json_data = request_data.json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 889, in json
    return complexjson.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1069 (char 1068)_

**Comment by mschmicking** [comment]
"MCU/Temperature" ist von Victron entfernt worden (zumindest in meinen OS wird der Key nicht erkannt und in der aktuellen Modbus Liste ist der Key ebenfalls draußen).
Die update Calls klappen bei neuere GO-E Charger Firmware nicht  mehr da die API sich geändert hat. 

Sollte mit #8  gelöst sein falls ihr beide Geräte aktualisiert. (getestet auf Go-Charger 56.1 und CerboOS 3.30).

**Comment by vikt0rm** [comment]
Ich habe soeben die hier beschriebenen Fehler behoben. Sollte mit dem letzten commit alles wieder funktionieren: https://github.com/vikt0rm/dbus-goecharger/commit/8940267b55576f172ba220300b9d1d0247df4cde

![Image](https://github.com/user-attachments/assets/61af8b1f-50fe-4498-9dca-bb212e8e2a38)
