### ISSUE TITLE
logfile owerflow

### ISSUE THREAD

**Issue by Justballer** [vikt0rm/dbus-goecharger#7]
Hi, 
a got a problem with my setup. Everything seems to work but the "current.log" is getting full with following error messeges and the display on VRM ist frozen.

2023-09-27 14:22:49,617 root INFO Start
2023-09-27 14:22:49,638 root CRITICAL Error at main
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 262, in main
    pvac_output = DbusGoeChargerService(
  File "/data/dbus-goecharger/dbus-goecharger.py", line 25, in __init__
    config = self._getConfig()
  File "/data/dbus-goecharger/dbus-goecharger.py", line 80, in _getConfig
    config.read("%s/config.ini" % (os.path.dirname(os.path.realpath(__file__))))
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/data/dbus-goecharger/config.ini', line: 2
'AccessType = OnPremise\n'
2023-09-27 14:22:52,669 root INFO Start
2023-09-27 14:22:52,681 root CRITICAL Error at main
Traceback (most recent call last):
  File "/data/dbus-goecharger/dbus-goecharger.py", line 262, in main
    pvac_output = DbusGoeChargerService(
  File "/data/dbus-goecharger/dbus-goecharger.py", line 25, in __init__
    config = self._getConfig()
  File "/data/dbus-goecharger/dbus-goecharger.py", line 80, in _getConfig
    config.read("%s/config.ini" % (os.path.dirname(os.path.realpath(__file__))))
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)

<img width="375" alt="20230927_135742908_iOS" src="https://github.com/vikt0rm/dbus-goecharger/assets/117982038/30999925-1770-494b-aefb-65a2fdc3c06e">

Can someone help me?

**Comment by Justballer** [comment]
I could solve the problem with deleting and reinstalling the script.
